var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.eai3r._.js")
R.c("server/chunks/ssr/0prs_next_dist_esm_build_templates_app-page_0q2_5uv.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bp2mww._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i1yhln._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/0prs_next_dist_client_components_0qoc4cy._.js")
R.c("server/chunks/ssr/0prs_next_dist_client_components_builtin_forbidden_0dnem6k.js")
R.c("server/chunks/ssr/0prs_next_dist_client_components_builtin_unauthorized_0qx0g~0.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0eq97pa.js")
R.m(38824)
module.exports=R.m(38824).exports
